# Generated by Django 2.0.5 on 2018-08-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('radius', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('x', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('z', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('texture_map', models.CharField(blank=True, max_length=50, null=True)),
                ('bump_map', models.CharField(blank=True, max_length=50, null=True)),
                ('specular_map', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('radius', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('x', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('z', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('texture_map', models.CharField(blank=True, max_length=50, null=True)),
                ('abs_mag', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('color_index', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('luminosity', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
            ],
        ),
    ]
