# Generated by Django 2.0.5 on 2018-08-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universejs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='bump_map',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='specular_map',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='texture_map',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='texture_map',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
